name: Build-Push and Deploy to EC2

on:
  workflow_dispatch:  
  push:
    branches:
      - main

env: 
  BACKEND_IMAGE_NAME: toufikj/discoverdoller-backend
  FRONTEND_IMAGE_NAME: toufikj/discoverdoller-frontend      
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USER}}
          password: ${{secrets.DOCKER_PASS}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Build and Push to Docker Hub for Backend
        uses: docker/build-push-action@v5.1.0
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: |
            ${{ env.BACKEND_IMAGE_NAME }}:latest 
            
      - name: Build and Push to Docker Hub for Frontend
        uses: docker/build-push-action@v5.1.0
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: |
            ${{ env.FRONTEND_IMAGE_NAME }}:latest      

      - name: SSSH and Deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.PUBLIC_IP }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY_PAIR }}
          port: "22"
          script: |
            cd ~/discoverdoller
            git pull origin main
            docker-compose pull
            docker-compose up --remove-orphans -d
            docker system prune -af